### PR TITLE
GEODE-2554 Add htaccess file for docs redirect

### PR DESCRIPTION
**Pull request by joeymcallister**

### CODE REVIEW

**Review by davebarnes97 — APPROVED** [review]
+1 LGTM
Need to deploy in order to test. Not the usual order of doing things, but how it must be done in this case. Low risk, if any.

**Comment by metatype** [comment]
Not sure why travis is unhappy.  Perhaps we need to override the `install` directive to prevent it from trying to run `gradlew assemble`.

**Comment by metatype** [comment]
I think the rules should be:

```
RewriteRule /guide/latest/(.*)$ /guide/11/$1 [R=303,NC,L]
RewriteRule /guide/(.*)$ /guide/11/$1 [R=303,NC,L]
```

You can check this at a site like http://htaccess.mwl.be on 
```
https://geode.apache.org/docs/guide/configuring/running/running_the_cacheserver.html
https://geode.apache.org/docs/guide/latest/configuring/running/running_the_cacheserver.html
```

**Comment by joeymcallister** [comment]
@metatype Thanks for looking at the Travis issue.

I get what you're saying with the second RewriteRule, but my concern is that it also would impact directories that shouldn't be impacted, like `11`, `10`, and soon `12`. In other words, it would redirect `/guide/11/` to `/guide/11/11/`.

I spent the past couple of weeks submitting to Google's My Removal Requests page every search result pointing to `/docs/guide/...`. There may be a few stragglers, but Google should zap them when it eventually re-crawls the Geode site. Not creating a redirect to the files at `guide/` might cause some short-term strife with broken links from, for instance, the wiki, but I think the impact will be minimal and may be remedied by fixing the broken links to point to the new `guide/latest/` locations.

I _could_ create redirects for each of the files and directories within `guide` that we want redirected to `latest`, but that seems more like a bandage that eventually would need to be removed anyway.

What do you think?

**Comment by metatype** [comment]
Whoops, you're right.  Ok, let's just do the latest -> 11 rule.

**Comment by metatype** [comment]
What's the status of this PR?

**Comment by joeymcallister** [comment]
Closing. `Latest` points to the latest version now.

**Pull request closed without merging**
